### ISSUE TITLE
Links to Articles

### ISSUE THREAD

**Issue by kingsleyramos** [onecheesepizza/project-1#14]

**Comment by zaydalashini** [comment]
https://www.latimes.com/food/la-fo-orleans-and-york-20190206-story.html

https://la.eater.com/2015/5/6/8561235/orleans-york-downtown-po-boy-opening-report-expansions

https://www.latimes.com/food/dailydish/la-dd-muffaletta-orleans-york-deli-20150519-story.html 

^ I think this should be like at the bottom of the homepage with a link that says "Featured and logos of the publications and once you link on them it goes to the articles"
