### ISSUE TITLE
Research PayPal Accessibility Plugin

### ISSUE THREAD

**Issue by onecheesepizza** [onecheesepizza/project-1#20]
Research PayPal Accessibility Plugin 
http://paypal.github.io/bootstrap-accessibility-plugin/

**Comment by onecheesepizza** [comment]
Accessibility Research and Resources: https://docs.google.com/document/d/1vMXJZ0HFBZ0BD5fVdFXxP-T_HacWoH4AoCIdh64zS2A/edit?usp=sharing

Upon further research, the PayPal Bootstrap Accessibility Plugin is not necessary for the latest version of Bootstrap (4), which fixes most of the accessibility problems that Bootstrap 3 had. Accessibility research, resources, and and testing tools are linked above.

**Comment by zaydalashini** [comment]
Oh wow. Thats great
