### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by zaydalashini** [onecheesepizza/project-1#5]

**Comment by onecheesepizza** [comment]
approved by Omar. 
proposal: https://docs.google.com/document/d/1TqYQT9JilwXuLSvhn2dL48lPSNRV5PNZ5rLMkgSiKSc/edit?ts=5dafbc19
see notes in project resources: https://docs.google.com/document/d/1z-bofRxsi_SdfldTKqo5J617RrNyCtvZzSdRoNpB68w/edit
